name: CI
on:
  [ push ]
jobs:
  container-test-job:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '10'
      - run: sudo sh test/unix/wrongJavaInstalled.sh