name: CI
on:
  [ push ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container: maven:3.8.6-eclipse-temurin-11-alpine
    steps:
      - uses: actions/checkout@v3
      - name: tests
        run: mvn test