name: CI
on: push
jobs:
  icaro-installed-on-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - run: |
          touch ~/.zshrc
          mvn clean package
          java -jar target/cli-installer-0.1-alpha.1-jar-with-dependencies.jar
          source ~/.zshrc
          icaro