name: CI
on: push
jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-java@v3
      - uses: actions/checkout@v3
        with:
          distribution: 'corretto'
          java-version: '11'
      - name: pwsh
        shell: pwsh
        run: ./src/windows.ps1
      - name: powershell
        shell: powershell
        run: ./src/windows.ps1