name: CI
on: push
jobs:
  wrong-installed-java:
    runs-on: [ macos-latest, ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      - run: sudo sh test/unix/wrongJavaInstalled.sh