name: CI
on: push
jobs:
  icaro-installed-on-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - run: |
          #!/bin/sh >> ~/.zshrc
          mvn clean package
          java -jar target/cli-installer-jar-with-dependencies.jar
          source ~/.zshrc
          cat ~/.zshrc
          ls ~/icaro
          ls ~/icaro/lang
          ls ~/icaro/cli
