name: CI
on: push
jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        shell: pwsh
        run: ./src/windows.ps1
      - uses: actions/checkout@v3
        shell: powershell
        run: ./src/windows.ps1