name: CI
on: push
jobs:
  icaro-is-correctly-installed-on-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - run: sh test/macos.sh
